name: Deploy to Lightsail

on:
  push:
    branches: [ production ]

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '18.16.0'

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3.2.0
      with:
        dotnet-version: '7.0'

    - name: Install npm dependencies and build client app
      env:
        VITE_ROOT_URL: '/'
        VITE_CLOUD_FRONT: 'https://dayocmrg0m9gc.cloudfront.net'
      run: |
        cd Client
        npm install
        npm run build
        cd ..

    - name: App Settings Variable Substitution for .NET
      uses: microsoft/variable-substitution@v1
      with:
        files: '${{env.DOTNET_ROOT}}/Seaweed/API/appsettings.json'
      env:
        Psql__ConnectionString: ${{ secrets.PSQL_CONNECTIONSTRING }}
        Jwt__Key: ${{ secrets.JWT_KEY }}
        Jwt__Issuer: ${{ secrets.JWT_ISSUER }}

    - name: Publish .NET app
      run: |
        cd API
        dotnet publish -c Release

    - name: Copy files to Lightsail instance
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.LIGHTSAIL_IP }}
        username: ${{ secrets.LIGHTSAIL_USERNAME }}
        key: ${{ secrets.LIGTHSAIL_KEY }}
        port: 22
        source: "API/bin/Release/net7.0/publish/"
        target: "/var/www/myaspnetcore/"
